# SPDX-FileCopyrightText: 2026 Blender Authors
#
# SPDX-License-Identifier: GPL-2.0-or-later
#
# AUTO-GENERATED - DO NOT EDIT. Regenerate: python tools/sysml/gen_kind_category.py
#
# SysML node kind -> metamodel category, derived from the node taxonomy.
# Used by sysml_structure.py to validate reference-socket wiring.

KIND_CATEGORY = {
    "SysMLNodeActionDef": "definition",
    "SysMLNodeActionUsage": "usage",
    "SysMLNodeAlias": "alias",
    "SysMLNodeAllocationDef": "definition",
    "SysMLNodeAllocationUsage": "usage",
    "SysMLNodeAnalysisCaseDef": "definition",
    "SysMLNodeAnalysisCaseUsage": "usage",
    "SysMLNodeAttributeDef": "definition",
    "SysMLNodeAttributeUsage": "usage",
    "SysMLNodeBindingUsage": "usage",
    "SysMLNodeCalcDef": "definition",
    "SysMLNodeCalcUsage": "usage",
    "SysMLNodeCaseDef": "definition",
    "SysMLNodeCaseUsage": "usage",
    "SysMLNodeComment": "annotation",
    "SysMLNodeConcernDef": "definition",
    "SysMLNodeConcernUsage": "usage",
    "SysMLNodeConjugatedPortDef": "definition",
    "SysMLNodeConnectionDef": "definition",
    "SysMLNodeConnectionUsage": "usage",
    "SysMLNodeConstraintDef": "definition",
    "SysMLNodeConstraintUsage": "usage",
    "SysMLNodeDocumentation": "annotation",
    "SysMLNodeEnumerationDef": "definition",
    "SysMLNodeEnumerationUsage": "usage",
    "SysMLNodeFlowDef": "definition",
    "SysMLNodeFlowUsage": "usage",
    "SysMLNodeImport": "import",
    "SysMLNodeInterfaceDef": "definition",
    "SysMLNodeInterfaceUsage": "usage",
    "SysMLNodeItemDef": "definition",
    "SysMLNodeItemUsage": "usage",
    "SysMLNodeLibraryPackage": "package",
    "SysMLNodeMetadataDef": "definition",
    "SysMLNodeMetadataUsage": "usage",
    "SysMLNodeOccurrenceDef": "definition",
    "SysMLNodeOccurrenceUsage": "usage",
    "SysMLNodePackage": "package",
    "SysMLNodePartDef": "definition",
    "SysMLNodePartUsage": "usage",
    "SysMLNodePortDef": "definition",
    "SysMLNodePortUsage": "usage",
    "SysMLNodeReferenceUsage": "usage",
    "SysMLNodeRenderingDef": "definition",
    "SysMLNodeRenderingUsage": "usage",
    "SysMLNodeRequirementDef": "definition",
    "SysMLNodeRequirementUsage": "usage",
    "SysMLNodeStateDef": "definition",
    "SysMLNodeStateUsage": "usage",
    "SysMLNodeSuccessionUsage": "usage",
    "SysMLNodeUseCaseDef": "definition",
    "SysMLNodeUseCaseUsage": "usage",
    "SysMLNodeVerificationCaseDef": "definition",
    "SysMLNodeVerificationCaseUsage": "usage",
    "SysMLNodeViewDef": "definition",
    "SysMLNodeViewUsage": "usage",
    "SysMLNodeViewpointDef": "definition",
    "SysMLNodeViewpointUsage": "usage",
}
