/* SPDX-FileCopyrightText: 2026 Blender Authors
 *
 * SPDX-License-Identifier: GPL-2.0-or-later */

/** \file
 * \ingroup nodes
 *
 * Element model → bpy graph-builder `.py` (BSML3 / SCRUM-500). Emits a script
 * that rebuilds the SysML node graph through the public `bpy` RNA — the same
 * `element_name` / `multiplicity` / `is_abstract` properties and relationship
 * sockets the importer populates — so `graph → .py → graph` reproduces the
 * source. Nodes are created in a stable order and referenced by index; every
 * link feeds a target's `self` output into the referencing node's socket.
 */

#include "NOD_sysml_export.hh"

#include "export_model.hh"

#include <cstdio>
#include <fstream>
#include <string>
#include <unordered_map>
#include <vector>

#include "DNA_node_types.h"

namespace blender::nodes::sysml {

/* A Python double-quoted string literal for `s`. */
static std::string py_str(const std::string &s)
{
  std::string out = "\"";
  for (const char c : s) {
    if (c == '\\' || c == '"') {
      out += '\\';
      out += c;
    }
    else if (c == '\n') {
      out += "\\n";
    }
    else {
      out += c;
    }
  }
  out += '"';
  return out;
}

static std::string py_float(const float f)
{
  char buf[32];
  std::snprintf(buf, sizeof(buf), "%g", double(f));
  return buf;
}

static std::string build_script(const bNodeTree &tree, const ExportModel &model)
{
  std::unordered_map<const ExportElement *, int> index;
  for (size_t i = 0; i < model.elements.size(); i++) {
    index[model.elements[i].get()] = int(i);
  }

  std::string s;
  s += "# Auto-generated by Blender-SML: bpy graph-builder for a SysML node tree.\n";
  s += "# Run inside Blender (blender --background --python this_file.py) to rebuild the graph.\n";
  s += "import bpy\n\n";
  s += "tree = bpy.data.node_groups.new(" + py_str(tree.id.name + 2) + ", \"SysMLNodeTree\")\n\n";
  s += "def _sock(node, ident, out=False):\n";
  s += "    for s in (node.outputs if out else node.inputs):\n";
  s += "        if s.identifier == ident:\n";
  s += "            return s\n";
  s += "    raise KeyError(ident)\n\n";
  s += "nodes = []\n";

  for (const std::unique_ptr<ExportElement> &element : model.elements) {
    const ExportElement &e = *element;
    s += "n = tree.nodes.new(" + py_str(e.idname) + ")\n";
    if (!e.name.empty()) {
      s += "n.element_name = " + py_str(e.name) + "\n";
    }
    if (!e.multiplicity.empty()) {
      s += "n.multiplicity = " + py_str(e.multiplicity) + "\n";
    }
    if (e.is_abstract) {
      s += "n.is_abstract = True\n";
    }
    s += "n.location = (" + py_float(e.node->location[0]) + ", " +
         py_float(e.node->location[1]) + ")\n";
    s += "nodes.append(n)\n";
  }
  s += "\n";

  /* Links: every relationship feeds the referenced element's `self` output into
   * this node's input socket (containment = child.self -> parent.members). */
  const std::pair<const std::vector<ExportElement *> ExportElement::*, const char *> slots[] = {
      {&ExportElement::members, "members"},
      {&ExportElement::of, "of"},
      {&ExportElement::specializes, "specializes"},
      {&ExportElement::redefines, "redefines"},
      {&ExportElement::subject, "subject"},
      {&ExportElement::connect, "connect"},
      {&ExportElement::from, "from"},
      {&ExportElement::to, "to"},
  };
  for (const std::unique_ptr<ExportElement> &element : model.elements) {
    const ExportElement &e = *element;
    const int to_idx = index[&e];
    for (const auto &slot : slots) {
      for (const ExportElement *target : e.*(slot.first)) {
        const int from_idx = index[target];
        s += "tree.links.new(_sock(nodes[" + std::to_string(from_idx) +
             "], \"self\", out=True), _sock(nodes[" + std::to_string(to_idx) + "], \"" +
             slot.second + "\"))\n";
      }
    }
  }
  return s;
}

std::string export_sysml_bpy(const bNodeTree &tree)
{
  ExportModel model;
  build_export_model(tree, model);
  return build_script(tree, model);
}

int export_sysml_bpy_file(const bNodeTree &tree, StringRefNull filepath, std::string &r_report)
{
  ExportModel model;
  build_export_model(tree, model);
  const std::string script = build_script(tree, model);

  std::ofstream file(filepath.c_str(), std::ios::binary);
  if (!file) {
    r_report += "could not open file for writing: " + std::string(filepath.c_str()) + "\n";
    return -1;
  }
  file << script;
  if (!file) {
    r_report += "write error\n";
    return -1;
  }
  return int(model.elements.size());
}

}  // namespace blender::nodes::sysml
